### PR TITLE
added current styling for landing page

### PR DESCRIPTION
**Pull request by Chukslord1**
* Created components for Landing page
* Added styling 

This fixes issue #35

### CODE REVIEW

**Comment by litenull** [comment]
This seems like its not responsive. Is it easy to make it, just a little bit if possible?

**Comment by Chukslord1** [comment]
@litenull yes I should be able to make it responsive

**Comment by Chukslord1** [comment]
@litenull I have added the responsiveness

**Comment by litenull** [comment]
OK, This looks much better. Here are a couple more points.

Can you export the assets from Figma and add them in the design? The pictures, etc.
Also, there is a little margin on the borders, please add that. 
The text is not matching the design. 
There are problems with margins.

**Pull request merged**
